services:
  frontend:
    image: jasmineee0401/234-deploylab-frontend:latest
    pull_policy: always
    network_mode: host
    environment:
      - VITE_GRAPHQL_URI=http://120.26.174.241:8080/graphql
      - VITE_SERVER_URI=http://120.26.174.241:8080
    restart: unless-stopped
